export const products = [
  {
    "id": "coeur",
    "name": "Cœur",
    "theme": "Symboles",
    "stars": 1,
    "price": 1990,
    "gridW": 14,
    "gridH": 14,
    "tileSizeCm": 1.2,
    "image": "images/products/design-01.png",
    "artist": null,
    "description": "Un classique tout doux pour se lancer dans la mosaïque pixel art. Kit mini, idéal pour un premier essai ou une idée cadeau rapide."
  },
  {
    "id": "champignon",
    "name": "Champignon",
    "theme": "Nature",
    "stars": 1,
    "price": 1990,
    "gridW": 14,
    "gridH": 14,
    "tileSizeCm": 1.2,
    "image": "images/products/design-02.png",
    "artist": null,
    "description": "Un petit champignon rouge et blanc, parfait pour découvrir l'assemblage sans se prendre la tête."
  },
  {
    "id": "cactus",
    "name": "Cactus",
    "theme": "Nature",
    "stars": 2,
    "price": 2490,
    "gridW": 18,
    "gridH": 18,
    "tileSizeCm": 1.2,
    "image": "images/products/design-03.png",
    "artist": null,
    "description": "Un cactus graphique pour une déco murale qui ne demande aucun arrosage."
  },
  {
    "id": "etoile",
    "name": "Étoile",
    "theme": "Symboles",
    "stars": 2,
    "price": 2490,
    "gridW": 18,
    "gridH": 18,
    "tileSizeCm": 1.2,
    "image": "images/products/design-04.png",
    "artist": null,
    "description": "Une étoile pop en dégradé jaune/orange, à assembler en une soirée."
  },
  {
    "id": "vague",
    "name": "Vague",
    "theme": "Paysages",
    "stars": 3,
    "price": 3490,
    "gridW": 22,
    "gridH": 22,
    "tileSizeCm": 1.2,
    "image": "images/products/design-05.png",
    "artist": null,
    "description": "Une vague bleue minimaliste, pour les amateurs de déco épurée façon bord de mer."
  },
  {
    "id": "montagne",
    "name": "Montagne au couchant",
    "theme": "Paysages",
    "stars": 3,
    "price": 3490,
    "gridW": 22,
    "gridH": 22,
    "tileSizeCm": 1.2,
    "image": "images/products/design-06.png",
    "artist": null,
    "description": "Un coucher de soleil sur la montagne, dégradé violet-orangé, pour progresser en douceur."
  },
  {
    "id": "chat",
    "name": "Chat roux",
    "theme": "Animaux",
    "stars": 4,
    "price": 4490,
    "gridW": 28,
    "gridH": 28,
    "tileSizeCm": 1.2,
    "image": "images/products/design-07.png",
    "artist": null,
    "description": "Un chat roux plein de caractère, pour les mordus de patience qui veulent un vrai défi."
  },
  {
    "id": "paysage",
    "name": "Paysage de campagne",
    "theme": "Paysages",
    "stars": 5,
    "price": 5490,
    "gridW": 32,
    "gridH": 32,
    "tileSizeCm": 1.2,
    "image": "images/products/design-08.png",
    "artist": null,
    "description": "Notre kit le plus ambitieux : maison, montagnes, soleil et champs. Pour les expert·es de la mosaïque."
  },
  {
    "id": "hermine",
    "name": "Hermine",
    "theme": "Bretagne",
    "stars": 3,
    "price": 3490,
    "gridW": 20,
    "gridH": 20,
    "tileSizeCm": 1.2,
    "image": "images/products/design-09.png",
    "artist": null,
    "description": "Le motif héraldique breton, minimaliste en noir sur blanc. Une pièce discrète et identitaire, sans jamais utiliser le drapeau officiel."
  },
  {
    "id": "galette-saucisse",
    "name": "Galette-saucisse",
    "theme": "Bretagne",
    "stars": 2,
    "price": 2490,
    "gridW": 22,
    "gridH": 12,
    "tileSizeCm": 1.2,
    "image": "images/products/design-10.png",
    "artist": null,
    "description": "L'incontournable des fest-noz et pardons bretons, en version pixel art gourmande."
  },
  {
    "id": "galette-complete",
    "name": "Galette complète",
    "theme": "Bretagne",
    "stars": 3,
    "price": 3490,
    "gridW": 20,
    "gridH": 20,
    "tileSizeCm": 1.2,
    "image": "images/products/design-11.png",
    "artist": null,
    "description": "Jambon, œuf, fromage et sarrasin : la galette complète pliée en carré, jaune d'œuf bien visible au centre."
  },
  {
    "id": "cidre",
    "name": "Cidre en bolée",
    "theme": "Bretagne",
    "stars": 1,
    "price": 1990,
    "gridW": 18,
    "gridH": 18,
    "tileSizeCm": 1.2,
    "image": "images/products/design-12.png",
    "artist": null,
    "description": "La traditionnelle bolée de cidre breton, sans anse, remplie à ras bord. Un kit rapide à assembler."
  },
  {
    "id": "bretzel",
    "name": "Bretzel",
    "theme": "Alsace",
    "stars": 2,
    "price": 2490,
    "gridW": 12,
    "gridH": 14,
    "tileSizeCm": 1.2,
    "image": "images/products/design-13.png",
    "artist": null,
    "description": "Le bretzel alsacien, doré et parsemé de gros sel — premier motif de notre future collection Alsace."
  },
  {
    "id": "cigale",
    "name": "Cigale",
    "theme": "Sud",
    "stars": 2,
    "price": 2490,
    "gridW": 18,
    "gridH": 18,
    "tileSizeCm": 1.2,
    "image": "images/products/design-14.png",
    "artist": null,
    "description": "La cigale provençale, symbole du Sud, ailes déployées façon céramique de Provence."
  },
  {
    "id": "tropezienne",
    "name": "Tropézienne",
    "theme": "Sud",
    "stars": 1,
    "price": 1990,
    "gridW": 18,
    "gridH": 18,
    "tileSizeCm": 1.2,
    "image": "images/products/design-15.png",
    "artist": null,
    "description": "La brioche à la crème de Saint-Tropez, sucre perlé sur le dessus — un kit facile et gourmand."
  },
  {
    "id": "piment-espelette",
    "name": "Piment d'Espelette",
    "theme": "Pays basque",
    "stars": 1,
    "price": 1990,
    "gridW": 18,
    "gridH": 18,
    "tileSizeCm": 1.2,
    "image": "images/products/design-16.png",
    "artist": null,
    "description": "Le piment rouge suspendu sur les façades du Pays basque — premier motif de la future collection dédiée."
  },
  {
    "id": "rentree",
    "name": "Rentrée des classes",
    "theme": "Actualité",
    "stars": 2,
    "price": 2490,
    "gridW": 16,
    "gridH": 16,
    "tileSizeCm": 1.2,
    "image": "images/products/design-17.png",
    "artist": null,
    "description": "Un crayon jaune tout simple, en édition de saison pour la rentrée — un motif générique, sans aucune licence de marque."
  },
  {
    "id": "supporter",
    "name": "Esprit supporter",
    "theme": "Actualité",
    "stars": 1,
    "price": 1990,
    "gridW": 16,
    "gridH": 16,
    "tileSizeCm": 1.2,
    "image": "images/products/design-18.png",
    "artist": null,
    "description": "Un damier bleu-blanc-rouge pour vivre les grands événements sportifs aux couleurs de la France — motif générique, sans logo ni fédération."
  }
];
